### ISSUE TITLE
Option to disable "back and forth" animation on Windows

### ISSUE THREAD

**Issue by ghost** [ryukinix/mal#66] opened 2017-10-02 20:32 UTC
In a default Windows command prompt, the fancy loading animation causes some nasty output due to the lack of proper support for symbols/colors in cmd. Powershell does the same thing. Here is an example of how it looks:
`????????? ? matching animes - preparing animes ▄←[G←[K←[G←[KMatched 17 items:`

Would it be possible to have a config option that would disable that animation?

Edit: It's obviously low-priority (as it is aesthetics) but I would be more than happy to write it myself and submit a pull request, if you wanted.

**Comment by ryukinix** [comment] 2017-10-02 20:46
Yes, this is a known issue, but is not filled here on issue tracker. The main reason is because support on Windows was not a important thing on beginning. At first, I did need properly setup a way on [decorating] to easily disable the decorating animation without effort. After that we can create a flag to disable or just setup that on config file.

[decorating]: https://github.com/ryukinix/decorating

**Comment by ryukinix** [comment] 2017-10-02 20:47
We even disable this for default on Windows... since I think this always the expected behavior (since doesn't works).

**Comment by ryukinix** [comment] 2017-10-02 20:50
But you can record a simple gif of this behavior? If the problem is just the characters, maybe implementing this [decorating/issue/30] here will take care of that using only ASCII code (not unicode as is using now). But if even the ANSI characters used to update the line is not working, we will need disable the animation totally.

To record a gif on windows I recommend [GifCam].

[GifCam]: http://blog.bahraniapps.com/gifcam/
[decorating/issue/30]: https://github.com/ryukinix/decorating/issues/30

**Comment by ghost** [comment] 2017-10-02 20:59
I believe the animation would work on Windows if you use a third-party terminal, so a config option might be best rather than outright disabling it for Windows.

Here is what it looks like:
![Windows Animation](https://i.imgur.com/FYi4Kph.gif)

**Comment by ryukinix** [comment] 2017-10-02 21:06
Thanks for the gif. The erase method seems not working very well too, but at least is not worse I executed before, which the animation will delete all your output of terminal (even C:\Window... and another thing that was printed before :v).

Yes, executing through cygwin or mingw will probably works, but not through the default Windows ancient terminal `cmd.exe` since is not a POSIX environment (I need to be POSIX), even the PowerShell. But see that running through environments like cygwin or mingw we will have different signatures of `sys.platform`, see [here]. So is safe disable to `sys.platform == 'win32'`. 

[here]: https://docs.python.org/3.5/library/sys.html#sys.platform

**Comment by ryukinix** [comment] 2017-12-27 10:30
Since I have released v0.6.1 of [`decorating`](https://github.com/ryukinix/decorating/blob/master/CHANGELOG) library used for this back-forth animation, I can disable/enable this animation globally by:

```python
import decorating
# to disable the animations
decorating.animated.enabled = False 
# to enable again
decorating.animated.enabled = True

```

**Comment by ryukinix** [comment] 2017-12-31 02:22
~I'll create a flag for disable the animation for now as went requested. As further work, we can look about handle this better on Windows.~


- [x] create a option on config file to disable the animation calling

EDIT:
I'm thinking a little that would be nice have this behavior to be possible to setup on the config file as well because is too painful calling --disable-animation always

**Comment by ryukinix** [comment] 2017-12-31 12:53
After #77 merged @logan-arens you can disable this option on the config file. Call `mal config` to get the path of file and a preview of how it looks.

**Closed as completed** 2017-12-31 15:37 UTC
Labels: os:windows, status:reproducible
